export const networkError = {
  401: "Unauthorized",
  403: "Forbidden",
  404: "Not found",
  500: "Internal server error",
  502: "Bad gateway",
  503: "Service unavailable",
  504: "Gateway timeout",
  400: "Bad request",
  405: "Method not allowed",
  429: "Too many requests",
  408: "Request timeout",
  0: "Network error",
  default: "Something went wrong",
};
